version: '3.8'

services:
  transitgpt:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - GROQ_API_KEY=your_groq_api_key
      - ANTHROPIC_API_KEY=your_anthropic_api_key
      - GMAP_API=your_google_maps_api_key
    command: streamlit run chat_app.py 