[client]
showErrorDetails = true

[runner]
fastReruns = true

[server]
enableCORS = true
maxUploadSize = 512
maxMessageSize = 512
fileWatcherType = "auto"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[global]
showWarningOnDirectExecution = false